### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by Stranger6667** [kiwicom/schemathesis#30]
A CLI tool that will:

- generate test cases from the given schema (probably with an option to show them in stdout);
- execute these use cases against certain URL (if not specified in the schema);
- Pass certain config options to the relevant flow part (test generation / execution);

Possible examples:

Generate cases: 

```
schemathesis -s https://example.com/api/swagger.json --format=json
```

Execute: 
```
schemathesis run https://example.com/api/swagger.json
```

**Comment by Stranger6667** [comment]
The implementation could be based on #63

**Comment by paveldedik** [comment]
@Stranger6667 I don't understand this - what exactly do we want to generate here? I'm talking about this command:

```
schemathesis -s https://example.com/api/swagger.json --format=json
```

What should be the output? And how will the output be used? Should it be just a JSON file containing generated some data representing different cases (inputs for the test function)?

I want to understand why it would be useful, since the second command would do the same as the first one, only without outputting the cases. It just generates the cases and runs the test function, the only argument needed is the swagger.json schema file.

The second command would be implemented easily using the `runner.execute` function. The first command would be about serializing/deserializing the generated cases, easy - but I want to make sure I not missing something here as I'm not sure about use cases.

**Comment by Stranger6667** [comment]
The initial idea was to be able to run each phase separately, but probably it should be decided later, since now it is not clear how useful it will be, indeed. I think we can start with `run` command and then extend the CLI if needed

**Comment by paveldedik** [comment]
Yep, I agree with you, if there isn't any specific case where it would be useful to have the first command, I would skip it for now.

I will implement the `run` command.
