### ISSUE TITLE
Add hooks to modify request before request is sent

### ISSUE THREAD

**Issue by barrett-schonefeld** [kiwicom/schemathesis#458]
### Description

Schemathesis currently has hooks that allow users to extend the set of Schemathesis validation functions. I would like to be able to write hooks that allow me to alter the request before it is sent to the API. This will allow me to test specific behavior of the API. 

Example of one extended validation rule: 

    Accept header MUST be used to indicate allowable request methods in a 405 response.

To exercise this validation rule, we need to send a request with an operation that we know is not in the API definition for that endpoint. This idea is mentioned in #108, so this behavior may be included as part of the broader goal to generate invalid data in #65.

However, some of the rules are likely too specific to be part of the default request generation. For example:

    Requests including Accept header with only formats not supported by the server MUST be
    rejected with a 406 status code and appropriate error response model.

### Design

The validation hooks are simple and easy to use, and I think the request hooks should use the same design with different parameters. I think the should request hooks should take a request object and a case object (or any object that contains the API description for the endpoint associated with the request).

### Questions to Consider

- Does mutating an initially valid request cause problems?
- Do the extended validation rules still run when the status code is not in the API definition? 415 response, for example, may not be documented in the OpenAPI description.
- Which requests do we modify? We only want to modify a subset of the requests. Maybe we generate a valid request for each hook in addition to the default requests. Each additional valid request will be modified by a single hook.

**Comment by Stranger6667** [comment]
Hi @barrett-schonefeld !
Thank you for the proposal, I like it a lot :) Here are my answers to the questions above:
1. No, it should not. It is actually constructed from a `Case` instance [here](https://github.com/kiwicom/schemathesis/blob/master/src/schemathesis/models.py#L123). Maybe it will be enough for a hook to take only a `Case` instance then. What do you think? E.g. a hook might be called right after `case` creation
2. Checks are called on all responses ([code](https://github.com/kiwicom/schemathesis/blob/master/src/schemathesis/runner/impl/core.py#L130)). Most probably `status_code_conformance` will fail if any not documented response code will appear (and there is no `default` included in `responses`)
3. Hm, it feels like filtration should be on the hook side, so the user may decide what to modify. 

Re: generating extra requests. I am not sure, actually, need to re-check the architecture and think more about it. E.g. how to report the results from such modified requests

**Comment by barrett-schonefeld** [comment]
Great, I have a couple follow-ups!

Before I start, though, I want to explain how I envision the hooks working for the particular use case I described. I am imagining that, if Schemathesis is configured to generate 10 tests for one operation and I've written 5 request hooks, I imagine Schemathesis sending 15 requests to the API. This way the original suite of 10 Schemathesis tests is still sent to the API. Then, those 5 request hooks essentially represent some additional unit tests on the API (for example, what does the API do if I send an invalid `Accept` header with an otherwise valid request?). I am completely open to suggestions on this design, and I just wanted to explain my own biases on this issue.

1. Is there 1 `Case` object per test or 1 `Case` object per endpoint? If there is 1 `Case` object per endpoint, mutating the `Case` object would change all generated requests for that endpoint. If there is 1 `Case` object per test, passing the request hook only a `Case` object should work great. (My confusion might be illustrated in [this comment](https://github.com/kiwicom/schemathesis/issues/454#issuecomment-608038807) I wrote. I noticed differences between the `Case` object's fields and `response.request` object.)
2. That's great for the use case I'm describing!
3. I described a "`beforeOne`" hook below. If we let the hooks do the filtering, each hook would not be aware of whether they have been applied to a request yet.

I thought of a different way to describe what I'm imagining. You may already be familiar with [Dredd hooks](url). Dredd only generates one test per operation (or maybe status code), while Schemathesis by default generates many. What I'm describing would be like a `beforeOne` hook where the hook is performed arbitrarily on only one of the generated requests. The hook would represent a unit test, so we don't want to apply it to all the requests because it would potentially disrupt other tests.

Please let me know what you think! I think it'd be great to have multiple kinds of hooks similar to Dredd's hooks.

**Comment by barrett-schonefeld** [comment]
Update:

I previously thought there was a difference between the request data in the `Case` object and the `Response.request` object, but I was wrong.

After further investigation, they seem to be the same. This means my answer to the first point should have been:

1. Yes, I agree! It would be enough to pass the hooks a `Case`, and the hooks could execute right after the `Case` is created.

**Comment by Stranger6667** [comment]
Great! Today I was drafting some ideas on hooks, compared them to the Dredd's ones - will share the outcomes of hooks design in a few days :)

**Comment by MohitKumar1991** [comment]
@Stranger6667  Thank you for your replies on #514 . If it's possible to contribute I would like to start with this issue as after this issue we will be able to switch our internal fork to the main repository.

**Comment by MohitKumar1991** [comment]
Here are some of the use cases hooks can be used for:-
1. Adding unknown methods
2. Adding extra examples
3. Changing parameters of the request
4. Create simple workflows where we can use the response of one request into another. For instance consider a simple scenario of uploading a file and adding it to a document. Usually the file will have to be uploaded first and then the same id will have to be used to add it to the document.
5. Adding connection objects to the runner, for instance a custom session object to the runner.
6. Adding extra details to TestResult from Response. This would be helpful to generate custom reports.
7. Injecting/Changing Hypothesis Strategies on the fly.
8. Be able to extend schemathesis for OpenAPI Extensions.

**Comment by MohitKumar1991** [comment]
My intention is now to list all possible hooks.

```python
def BeforeInit(ExecutionContext, Schema):
  pass

def Initialized(ExecutionContext, Schema):
   pass

def BeforePath(): 
   pass

def BeforeEndpoint():
   pass

def BeforeCase():
   pass

def BeforeChecks()
   pass

def AfterChecks():
  pass

def AfterCase():
   pass

def AfterEndpoint():
  pass

def AfterPath(): 
   pass

def AfterAll():
   pass

def Finished():
   pass
```

**Comment by MohitKumar1991** [comment]
Instead of hooks, Template Tags like in Insomnia [here](https://support.insomnia.rest/article/40-template-tags) could be implemented and can solve most of the problems that hooks solve.

**Comment by Stranger6667** [comment]
Hi @MohitKumar1991 !
I'll take a look and will get back to you later :) Could you please provide some examples of how the tags concept can be applied?

**Comment by MohitKumar1991** [comment]
Yes so I am sure the docs explain it better than I do but I can explain in the context of the use cases I have written above.

Template Tags allow any of the parameters to be a template string instead of simple string. Insomnia does it with NunJucks who say they are inspired by Jinja2.

So for each Use case like this:-

- For Adding unknown methods method can be a template string with a function that resolves to GET,POST etc based on the example number.
- For simple workflows like getting tokens from a login request, we can inject Response object into the template and allow the template to store different values.
- Custom TestResults can be done by adding a json template string with response, request and other params

Insomnia can do all of these things in their UI and I checked their schema and it looks like this

`"{% response 'body', 'req_e63da43270304eacace169dd44bb242d',
          'b64::L2h0bWwvYm9keS9kaXZbNl0vZGl2WzNdL2Rpdls4XS9kaXZbMV0vZGl2WzJdL2R\
          pdg==::46b', 'no-history' %}"`

Which is { response responseParam requestId b64encodedXPath triggerParam }

**Comment by Stranger6667** [comment]
Folks, sorry for the delay. I have to fix a few regressions introduced in `1.3.0` and after it, I'll work in this direction

**Comment by barrett-schonefeld** [comment]
@MohitKumar1991 

This is great, and I like the ideas you are proposing! You mentioned the using data from one response as input to another request, and I think that is a great feature. We may want to consider [OpenAPI Links](https://swagger.io/docs/specification/links/) to do this. In fact, I should open an issue to discuss supporting OpenAPI Links.

Do you see a place for `beforeOne` hooks (described [above](https://github.com/kiwicom/schemathesis/issues/458#issuecomment-608104653)) in the list of hooks you created? I ask because it is important to me to be able to modify a request without having to know about the path names and operations in the OpenAPI description. I'm not sure what the `PATH X METHOD X PARAMS` notation represents, but it seems that the `beforeCase` hooks you mentioned could support the use case I described. If not that is OK because the hooks you described actually fit the name of this issue more closely.

@Stranger6667 Do you see a use case for the `beforeOne` hooks I described? The reason I want to include them is to provide a generalized way of modifying requests (without knowing the details of the OpenAPI description), and I'd be happy to contribute them upstream (I'd also be happy taking a step back if you think they fit into your proposal, @MohitKumar1991). Should I open a separate issue to track the type of hook I'm describing, or does it fit here?

**Comment by Stranger6667** [comment]
Hi :)

Open API Links - I didn't hear about this feature, but I think that it has a huge potential to increase the testing depth:
- Working with existing server-side data to avoid 404 (this functional was already implemented as extensions in https://github.com/arvindjangra1996/schemathesis and in #520 )
- It is standardized and deterministic (#520, in contrast, is based on the probability that certain endpoints are connected);
- Support can be added to Open API 2 via vendor extensions;
I still need to take a deeper look, but it seems like it might improve defects discovery dramatically. And probably it might be implemented as the next steps after hooks.

Re hooks. It seems to me that I finally came up with a design that I like which is similar to the pytest's one but simpler and backward compatible with the current hooks.
I, hopefully, will share it in the next few days and will try to address comments above more thoroughly so we all can connect our views and needs on this mechanism (sorry again @MohitKumar1991 for the delays).

> Do you see a use case for the beforeOne hooks I described?
Definitely. The use case seems perfectly valid to me, and it shouldn't be a problem to extend / add more hook points in the future

**Comment by barrett-schonefeld** [comment]
@Stranger6667 this is great! I'm excited to see the design for the hooks, and I'll be looking for ways to contribute.

**Comment by MohitKumar1991** [comment]
@barrett-schonefeld  OpenAPI links looks great :)

The template tags design by Insomnia looks more extensible and support more feature. However it is possible to implement that functionality by extending openapi links itself. For example:

OpenAPI Link is defined like this `$response.body#/username`

Instead of only $request/$response, we can allow custom objects. For instance I can inject an object called base64 which has two functions encode and decode. I can then define my parameters as:-

$base64.encode#/mohit

and this would provide the base64 encoded version of mohit.

**Comment by MohitKumar1991** [comment]
I could also have this in the response where I can store some parameter like this

$configStore.set#/url,$response.body#/new_url

**Comment by Stranger6667** [comment]
Hi folks!

Here is my draft for a more generic hooks mechanism - https://github.com/kiwicom/schemathesis/pull/547. It defines a minimal core tooling that can be used to define and apply new hooks. There are still some minor things in TODO, but it should show the possible interface for new hooks. I'd appreciate feedback and comments on it. I also thinking about some kind of separation for common hooks, runner-only hooks, and in-code hooks. For example, if we have a hook that modifies the request before sending then it is not really applicable in the in-code case - the user sends requests manually. What do you think?

@MohitKumar1991 
Regarding possible use cases - You provided much more usage examples than I was ever thinking of and I like all of them. Could you, please, provide more information on these ones?
- Custom session to the runner. Could you please describe for what purpose it could be useful? Maybe some custom auth? or e.g. making some extra requests for auth token and putting it into a new session?
- Open API extensions - do you mean to modify schema on the fly?

> I would also like a single context dict that will be passed along every hook. This can be used to store any values from response required for future execution.

Indeed, it will be helpful! I added a hook context recently, but it should be passed across different places - and probably in quite different ways in the runner and pytest plugin. I'll try to rethink it.

In general, I'd love to see these hooks implemented step by step so we can have a manageable change surface. I like the list of hooks you provided :) They seem to me like related to the runner only, right? I am wondering about that separation I mentioned above - some of these hooks might be used in regular in-code tests.

Re tags. It does seem interesting to me, but it is not clear to me how these tags could be integrated, what could the API look like?
However, it seems to me that this approach might add quite a lot of complexity and reduce flexibility since it is a special syntax to support and it wraps some logic that becomes not that visible to the user and also comes with some limitations. Now, the cost seems quite high to me in comparison with the possible benefit, at least at the moment - for me things become more clear when I see the API to use them :)
Rendering custom reports seems interesting, but it might be easier and more flexible for the end-user to implement template rendering on their side by using some hook. 
So, I need to think more about templates - I am concerned mostly about flexibility for the end-user.

Re custom functions in links. I am not sure - my first intention is to keep this syntax minimal to simplify implementation and reduce ambiguity (it also becomes much less introspectable for tools like IDE and syntax highlighters which might lead to more missed errors in these templates). However, I'd start with the standard syntax and then play with extending it, there are definitely workflows where it could be helpful but it is not yet visible to me.

Cheers :)

**Comment by Stranger6667** [comment]
@barrett-schonefeld I think it will be nice if you'll contribute that hook you needed when the hooks API will be stabilized - it should be about defining a hook spec and calling dispatch in the proper place

**Comment by MohitKumar1991** [comment]
@Stranger6667  Thanks for the consideration. 

Custom Session can help with custom authentication, End to End Encryption as well as custom SSL certificates. Urllib3 supports this out of the box. Here's the [link](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#custom-ssl-certificates).

OpenAPI Extensions can be used for implementation specific data. For instance AWS API Gateway related data for internal APIs. In both hooks and tags, what to do with extensions can be configured by the user.

My only issue with hooks is that it breaks all the business logic into YAML file as well as python code. Tags, Extensions and OpenAPI Links can help keep everything into the YAML file and hence much easier for the end user. For instance in my company multiple people will use the testing platform to test their own APIs. We can using hooks add custom logic on how to transform the request based on openapi extensions and then everyone can use those extensions knowing what they will do. 

Hooks, Links and Tags all look good to me as long as they keep all the business logic in the YAML file itself so only that file can be committed to git and tracked.

**Comment by barrett-schonefeld** [comment]
@Stranger6667 I was away for a couple of days, but I am looking over the merged hooks PR (#547)! I am going to start the implementation of the hook I described today. It may take me a bit to get my bearings, but I will open a PR for us to discuss/review the implementation once I have made significant progress.

**Comment by Stranger6667** [comment]
@barrett-schonefeld 
I'd be happy to take a look :) let me know if I can help there

@MohitKumar1991 
Thank you for providing more details! They definitely make things more clear to me :)

> My only issue with hooks is that it breaks all the business logic into YAML file as well as python code.

Interesting point! I didn't think about it from this point of view. Instead, I was thinking that the end-user will probably tend to work with Python code (I am obviously biased here since I have this preference).

> Hooks, Links and Tags all look good to me as long as they keep all the business logic in the YAML file itself so only that file can be committed to git and tracked.

Very well said, I understand your points and would be happy to support them from the Schemathesis side / accept contributions.

My current vision is somehow reminds me of `pytest` plugins & hooks system:
- Having a number of hooks inside Schemathesis that will make possible to adjust behavior in the way it is needed by your side;
- Keep Open API extensions processing separately from the core. For now, I see this quite abstract and therefore I think it will be easier to develop them separately and more adjusted for your use-case;

For example, if there is a hook `before_parse_link` that allows hooking into links parsing process - then by using this hook links' syntax can be extended and some custom tags can be used, etc. On the Schemathesis side, we can define it like this - if this hook is called and returned a result, then it should be used instead of the default processing. It is a quite abstract example, but I hope that it provides some more info on the idea

From what I see, these extensions have some specific role and use-case and I am not sure if they should be included in Schemathesis as is at least now.

**Comment by barrett-schonefeld** [comment]
@Stranger6667 @MohitKumar1991  I am closing this issue because I think we have satisfied this with #590, #547, #549, #551, etc.
