### ISSUE TITLE
Status codes in YAML document interpreted as integers

### ISSUE THREAD

**Issue by barrett-schonefeld** [kiwicom/schemathesis#513]
Example of response schema that produces the error (response code not explicitly wrapped in quotes):

    responses:
        200: ...

Initial error:

<img width="1296" alt="Screen Shot 2020-04-17 at 8 12 12 AM" src="https://user-images.githubusercontent.com/59850348/79611447-451fa780-80c0-11ea-91d4-251d543b1b96.png">

The exception referenced in the above image is raised in this this function:

    def _maybe_validate_schema(instance: Dict[str, Any], schema: Dict[str, Any], validate_schema: bool) -> None:
        if validate_schema:
            try:
                jsonschema.validate(instance, schema)
            except TypeError as t:
                raise ValidationError("Invalid schema")

I removed the try/except block to get the stack trace where the error occurs. `jsonschema` calls a Python regex function with the status code as an integer, but the argument must be a string.

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/59850348/79611407-30dbaa80-80c0-11ea-9906-1c7736cc0ee0.png">

Proposals:
1. The keys for responses should always be treated as strings.
2. _maybe_validate_schema should be updated to preserve the stack trace from the original exception.

**Comment by Stranger6667** [comment]
Hi!
Thank you for reporting this :)

1. Having response keys treated as strings is a bit problematic on the schemathesis level since it goes to validation logic from the `jsonschema` package. It would be nice if it won't fail there though but will be properly reported as a validation error without try except in schemathesis. I am not keen on adding special handling for schemas with errors since they are not predictable.

2. Hm, on supported Python versions these tracebacks should be chained, aren't they? With `The above exception was the direct cause of the following exception:` or a similar line

**Comment by Hultner** [comment]
The OpenApi-spec actually requires the status code to be quoted 

> ... This field MUST be enclosed in quotation marks (for example, "200") for compatibility between JSON and YAML...

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#patterned-fields-1

**Comment by barrett-schonefeld** [comment]
@Hultner great find, and thank you! My team discussed the issue and YAML keys were treated as implicit, but I think we were wrong. Regardless, we want our OpenAPI documents to comply with the OpenAPI spec.

@Stranger6667 

1. In light of @Hultner comment, I completely agree.

2. I'm using Python 3.7.6. I reproduced the error, and I do not see any reference to the root cause of the exception. The whole stack traceback is captured in the first image in the original issue description.

**Comment by Hultner** [comment]
> @Hultner great find, and thank you! My team discussed the issue and thought YAML keys were treated as implicit strings, but I think we were wrong. Regardless, we want our OpenAPI documents to comply with the OpenAPI spec.
> 
> @Stranger6667
> 
> 1. In light of @Hultner comment, I completely agree.
> 2. I'm using Python 3.7.6. I reproduced the error, and I do not see any reference to the root cause of the exception. The whole stack traceback is captured in the first image in the original issue description.

Yeah, YAML can be quite tricky, I've seen the implicit typecasting cause quite serious problems in large scale systems.

**Comment by Stranger6667** [comment]
@barrett-schonefeld 

Indeed, the cause is not caught, I missed it somehow :(

The fix is quite simple, I will add it soon.

Regarding having stricter YAML parsing. I think it is open for discussion as @Hultner proposed using `strictyaml` [package](https://github.com/crdoconnor/strictyaml), not sure can it be better utilized, but I think it worth considering (I discovered that I removed some of `pyyaml`'s implicit type conversions some time ago via `schemathesis.utils.StringDatesYAMLLoader`). But, I'd prefer to start this discussion in another issue + I'll open a PR for fixing that pattern properties behavior upstream in `jsonschema`
