### ISSUE TITLE
Support for warnings

### ISSUE THREAD

**Issue by barrett-schonefeld** [kiwicom/schemathesis#569]
In some cases, the user may want to be notified of a test failure without changing the exit code of the tests. This allows the user to be notified of errors while including Schemathesis in CI/CD build, and it may ultimately help the user incrementally improve their API.

To do this, it'd be nice to have configurable warnings for both the Schemathesis checks and the user's extended set of rules.

I'm plugging into the Schemathesis python code, so it is an option to write a new output handler. That means, however, the output handler would need to stay current with Schemathesis changes.

**Comment by Stranger6667** [comment]
What kind of warnings/notifications do you have in mind? Some Slack notification / gitlab comments or something different?

I think that we can add a feature to register custom event handlers, then it could be extended quite easily :)

**Comment by barrett-schonefeld** [comment]
I am thinking an additional section in the console output that would provide the same information as a failure. I am thinking any of the builtin checks or extended checks could be set to a warning. Any warning check failures would still be printed without changing the exit code:

    ======== WARNINGS ========
    1. Error message 
    ...

The primary goal with this feature is to keep the user aware of test failures by printing the warning, but if only warning checks fail, still give a successful exit code. This allows the user to stay aware of problems that they may not be able to fix until a later iteration while still getting a successful build on this iteration.

**Comment by Stranger6667** [comment]
> I am thinking an additional section in the console output that would provide the same information as a failure

So, the information will be duplicated there? I.e. both sections will be displayed?

If failures should not change the exit code, then the first idea that is coming to my mind is using `schemathesis ... || true`. What do you think about this approach? The downside is that errors will be also treated as 0 exit code. Now both errors and failures have the same exit code - 1. maybe we can distinguish and have different exit codes (e.g. 2 for errors), then on the shell level it should be easy to convert 1 to 0 but keep 2 as is, but depends on how you need to treat errors.

> This allows the user to stay aware of problems that they may not be able to fix until a later iteration while still getting a successful build on this iteration.

At work we usually mark such jobs as "allowed to fail", but not sure it if is applicable to your case, since it depends on the CI environment and workflows.

Let me know what do you think :) In any case, I think we can make the CLI handlers more flexible and I think it will worth it to move out exit code decision out of the `default` handler + allow adding new handlers

**Comment by barrett-schonefeld** [comment]
> So, the information will be duplicated there? I.e. both sections will be displayed?

If a check is marked as a warning and fails, the error message would only be displayed in the WARNINGS section.

I see your suggestions on `schemathesis ... || true` and "allowed to fail." However, we want to be specific about allowing failure only for a specific check. For one team, `status_code_conformance` may be a low priority and is OK to fail, but we may need a failed exit code and a failed build if we have `not_a_server_error`.

We are considering writing an output handler, but this could be a costly move because the output handler is an internal feature for Schemathesis, which means we would have to keep pace with any changes to internal Schemathesis APIs on which the output handler depends. So I think a way to extend the CLI handler is a great idea!

**Comment by Stranger6667** [comment]
>  However, we want to be specific about allowing failure only for a specific check

Aha, thank you for the clarification :) It sounds interesting to me and we can add some kind of configuration there.

Or additionally it could be some hook for event handling, I need to think more about it

**Comment by barrett-schonefeld** [comment]
@Stranger6667 yes, sounds great! Take some time to consider, and I'll comment here again if the issue gets pressed more on my side.

**Comment by barrett-schonefeld** [comment]
PR #575 satisfied this request.
