### ISSUE TITLE
Cassette support in wrapper CLI

### ISSUE THREAD

**Issue by barrett-schonefeld** [kiwicom/schemathesis#570]
Trying to add support for the Schemathesis cassettes in a wrapper CLI.

Wrapper CLI closely mimics Schemathesis CLI. In the Wrapper CLI, this is the command to invoke Schemathesis:

    execute(
        prepared_runner, DEFAULT_WORKERS, show_errors_tracebacks, store_network_log, None
    )

Resulting log.yaml file when run with wrapper CLI:

     command: '<unknown entrypoint>'
     recorded_with: 'Schemathesis 1.3.4'
     http_interactions:

Running the equivalent command in Schemathesis produces a valid log.yaml file. I saw the comment in the `cassettes.py` code that says the tool is meant to be used directly through Schemathesis CLI and not through `click.Context.invoke`. I would expect the wrapper CLI shown above should have almost the same behavior as the Schemathesis CLI. Does the wrapper pose the same problem as `click.Context.invoke`, or is the different behavior determined by the first arg of the CLI command `if not sys.argv[0].endswith("schemathesis"):`?

**Comment by Stranger6667** [comment]
> Does the wrapper pose the same problem as `click.Context.invoke`, or is the different behavior determined by the first arg of the CLI command if not `sys.argv[0].endswith("schemathesis"):`?

Yes. This behavior happens actually in almost all tests, except the one that is based on a sub-process call.
I choose this approach since it is the simplest one, alternatively, I was considering hooking into the click's command and saving arguments before they are processed by callbacks to have a proper, not processed argument list. When running not via the CLI, the command may actually look like this:

```
/usr/bin/python3.7 /path/to/python/file.py
```

in tests, it is a `pytest` call, etc. In other words, they are the actual args passed to the process entry point, which may be significantly different from what is passed to the runner.

Also, there is a conceptual separation:
- Runner.all the inside logic, emits events to the outside
- CLI. It consumes the runner events

And as the cassette wrapper is one of the handlers in CLI, it is intended to record the command passed to the CLI, not the runner arguments. The idea in my mind was to have a high-level reproduction code that can be copy-pasted and executed immediately and avoid some complex calls like PyCharm helper applies, but maybe it is actually more confusing than helpful in this case :(

Could you provide some more information about the goals of this wrapper? I think we can figure out some way to achieve those goals :)

**Comment by barrett-schonefeld** [comment]
Some general goals of the wrapper:

- In the wrapper, we have custom validation functions that represent API handbook rules. The wrapper invokes Schemathesis with these additional validation functions.
- The wrapper provides only a subset of the Schemathesis options. The wrapper limits the options to only those options our users will need.
- The wrapper sets default values for Schemathesis. For example, we are encouraging users to add examples to their API descriptions, so we set the default value for `hypothesis_phases` to explicit.

The goal with cassettes:

We want to support cassettes in the wrapper with the same interface and behavior as Schemathesis. The command would be:

    service-validator run path/to/schema --store-network-log=logs.yaml -b http://url.com

The service-validator CLI imports the `Runner.py` module, creates a `PreparedRunner`, and invokes the tests with `execute`. When the `store_network_log` flag is set, we'd like this to produce the same log of requests as it does in Schemathesis (although it is OK if the command name in the logs.yaml is <unknown command>).

**Comment by barrett-schonefeld** [comment]
I figured out the problem and will share the solution in case anyone else has the same obscure use case as me.

The cassettes implementation relies on the `AfterExecution.interactions` field. This field should have a list of `Interaction` objects that store information about the uri called, the HTTP method used, the response, etc.

The `AfterExecution.interactions` field was empty for me because the `store_interactions` parameter in `Runner.prepare` determines if interactions are stored and is False by default. I called `Runner.prepare` and set this value to True, which solved the problem.

**Comment by Stranger6667** [comment]
> although it is OK if the command name in the logs.yaml is <unknown command>

Okay :) I didn't understand that the issue was in that `store_interactions` key :(

Is there anything we can do here to support your use case?

**Comment by barrett-schonefeld** [comment]
@Stranger6667 

Sorry, my explanation above was not as clear as I thought! The use case is already supported, and I just need to make the following change on my side:

    runner.prepare(
        ...
        store_interactions=True
        ...
    )
