### ISSUE TITLE
Concurrent test execution only 2 thread 

### ISSUE THREAD

**Issue by dongfangtianyu** [kiwicom/schemathesis#579]
Looking at the code [src/schemathesis/runner/__init__.py#L191](https://github.com/kiwicom/schemathesis/blob/master/src/schemathesis/runner/__init__.py#L191) 

that the 'workers' parameter is not passed when constructing' ThreadPoolRunner'.

So, is this a  litle bug or other reasons?

**Comment by Stranger6667** [comment]
Oh, you are right! Indeed, I completely missed it :( Will fix it in a few minutes. Thank you for reporting this

**Comment by dongfangtianyu** [comment]
Is OK, It's a great honor to contribute to this  great tool

At the same time, I haveanother question,

According to the current design, threads get 'test' from the queue, so the number of endpoints determines the speed of parallel.

Can `case` be put into the queue and the thread get the case from the queue to execute? It could be faster?

**Comment by Stranger6667** [comment]
> Is OK, It's a great honor to do a litle contribute this great tool

I am glad to hear that :)

> Can case be put into the queue and the thread get the case from the queue to execute? It could be faster?

It depends on the overall system structure. In theory, it might be faster. Now each test is executed in a separate thread and has its own thread-local internal Hypothesis storage, which is test execution statistic, shrinking, etc. If we'll consider a design that you propose then there will be only one Hypothesis storage which will not actually work, because the execution of different cases will interfere with each other. My initial implementation take was with `aiohttp` and I faced exactly this problem - timeouts are shared, many other things are shared and it just doesn't work. It might work if these things will be stored as task-local in an async style, but it requires significant changes to Hypothesis, which, I assume, are too specific to the Schemathesis use-case.

But as an alternative it could be like this:
- tests are still in separate threads so Hypothesis-related things are isolated
- cases execution is pushed to another, IO thread which runs async network interactions

I am not sure about the performance though, it might be worth experimenting but no guarantees. Non-IO threads will be still waiting until the response will come from there IO thread, but it is hard to predict how this approach will behave.
